name: Check PRs

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.repository == `hypi-universe/docs`

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build
