name: Update search index

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.repository == 'hypi-universe/docs'
    container:
      image: algolia/docsearch-scraper:v1.13.0
      env:
        APPLICATION_ID: OR6SSGNSLB
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        #Based on https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json
        #See https://docsearch.algolia.com/docs/run-your-own/
        #and https://docsearch.algolia.com/docs/config-file/
        CONFIG: |
          {
            "index_name": "hypi",
            "start_urls": ["https://docs.hypi.app/docs"],
            "sitemap_urls": [
              "https://docs.hypi.app/sitemap.xml"
            ],
            "sitemap_alternate_links": true,
            "stop_urls": [],
            "selectors": {
              "lvl0": {
                "selector": "(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]",
                "type": "xpath",
                "global": true,
                "default_value": "Documentation"
              },
              "lvl1": "header h1",
              "lvl2": "article h2",
              "lvl3": "article h3",
              "lvl4": "article h4",
              "lvl5": "article h5, article td:first-child",
              "lvl6": "article h6",
              "text": "article p, article li, article td:last-child"
            },
            "strip_chars": " .,;:#",
            "custom_settings": {
              "separatorsToIndex": "_",
              "attributesForFaceting": [
                "language",
                "version",
                "type",
                "docusaurus_tag"
              ],
              "attributesToRetrieve": [
                "hierarchy",
                "content",
                "anchor",
                "url",
                "url_without_anchor",
                "type"
              ]
            },
            "conversation_id": [
              "833762294"
            ],
            "nb_hits": 16653
          }
    runs-on: ubuntu-latest
    steps:
    #https://hub.docker.com/layers/algolia/docsearch-scraper/v1.13.0/images/sha256-ca909fe6ac9757eb200dbf0e4eca068a9d2cd904273fb7f113264acc0635f0eb?context=explore
    - run: pipenv run python -m src.index

